### ISSUE TITLE
How to get the caption id ?

### ISSUE THREAD

**Issue by lerogo** [naver-ai/eccv-caption#3]
Hi naver-ai, 

Thanks for your excellent work.
Can you tell me how to get the caption id? 
Or can you send me a raw coco file？

Best, 
Hailang Huang

**Comment by SanghyukChun** [comment]
You can use pycocotools, the official COCO API. This is the easiest way to get caption ids

```
> pip install pycocotools
> python -c 'from pycocotools.coco import COCO; coco = COCO("/path/to/coco2014/annotations/captions_val2014.json"); print(list(coco.anns.keys()))'
```

Here is an example code:
https://github.com/naver-ai/pcme/blob/main/datasets/coco.py#L76

**Comment by lerogo** [comment]
The caption id means the pair id ?

e.g.
`{"image_id": 86468,"id": 821642,"caption": "a flower in a vase sits in the window"}`

`"id": 821642` means the caption id is 821642 ?

**Comment by lerogo** [comment]
Or in eccv caption, 
file `human_verified_caption_to_image.json`'s key is the pair `id`, and the value is the `image_id`
file `human_verified_image_to_caption.json`'s key is the `image_id`, and the value is the pair `id`

**Comment by SanghyukChun** [comment]
Yes. All of your words are correct

**Comment by lerogo** [comment]
thanks very much !!
